// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// import { CounterService } from "./worker/src";
type Default = import("./worker/src/index").default;

interface CloudflareEnv {
  // WORKER: Fetcher;
  WORKER: Service<Default>;
  ASSETS: Fetcher;
}
